title: Mölkulator
description: Mölkulator
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - index.md
  - privacy-policy.md
  - terms-and-conditions.md
